### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [qurator-spk/sbb_pixelwise_segmentation#5]
solved

**Comment by deepseek** [comment]
I also trained the text-lines as regions, and still not correctly detected.
[test2.zip](https://github.com/qurator-spk/sbb_pixelwise_segmentation/files/4007615/test2.zip)
Ground-Truth label, I modified the contrast so that you can see the masks:
![label](https://user-images.githubusercontent.com/49877135/71550870-4a5ec680-29eb-11ea-91c7-79478c19787b.jpg)
